"""数据模型层：Chunk、VectorRecord、Session/Memory、IngestTask、
TroubleshootingTask、Plan/Step、ToolDefinition 等 Pydantic 模型与统一错误模型。"""

from ghost_agent.models.chunk import Chunk
from ghost_agent.models.errors import (
    ChatTimeoutError,
    DimensionMismatchError,
    DuplicateTroubleshootingError,
    EmptyContentError,
    EmptyFileError,
    EmptyMessageError,
    ErrorCode,
    ErrorResponse,
    FileTooLargeError,
    GenerationError,
    GenerationTimeoutError,
    GhostAgentError,
    IngestFailedError,
    IterationLimitReachedError,
    McpConnectFailedError,
    McpToolError,
    McpToolTimeoutError,
    MemorySummarizeFailedError,
    MessageTooLongError,
    MissingTroubleshootFieldsError,
    ParseFailedError,
    ParseTimeoutError,
    QueryEmbeddingFailedError,
    QueryEmptyError,
    ReplanLimitReachedError,
    SSEIdleTimeoutError,
    SendMsgFailedError,
    ServiceUnavailableError,
    SourceFileNotFoundError,
    SplitFailedError,
    SyncFailedError,
    TargetGroupUnavailableError,
    TemplateNotFoundError,
    ToolNamingConflictError,
    ToolNotFoundError,
    ToolValidationError,
    UnsupportedFileTypeError,
    UnsupportedTechStackError,
    VectorDatabaseUnavailableError,
    WebhookSignatureInvalidError,
)
from ghost_agent.models.ingest_task import IngestTask, IngestTaskStatus
from ghost_agent.models.memory import (
    LongTermSummary,
    Message,
    Role,
    Session,
    ShortTermMemory,
)
from ghost_agent.models.plan import (
    Plan,
    ReplanVerdict,
    Step,
    StepFailure,
    StepResult,
    StepStatus,
)
from ghost_agent.models.tool import (
    ParamDef,
    ParamType,
    ToolDefinition,
    ToolSource,
)
from ghost_agent.models.troubleshooting_task import (
    NO_CONTENT,
    AlarmInfo,
    AnalysisSummary,
    ReportStatus,
    TriggerType,
    TroubleshootingTask,
    TroubleshootingTaskStatus,
)
from ghost_agent.models.vector_record import VectorRecord, VectorType

__all__ = [
    # ----- 错误模型 -----
    "ErrorCode",
    "ErrorResponse",
    "GhostAgentError",
    # API 接口层异常
    "EmptyMessageError",
    "MessageTooLongError",
    "ChatTimeoutError",
    "GenerationError",
    "GenerationTimeoutError",
    "SSEIdleTimeoutError",
    "EmptyFileError",
    "UnsupportedFileTypeError",
    "FileTooLargeError",
    "IngestFailedError",
    "MissingTroubleshootFieldsError",
    "WebhookSignatureInvalidError",
    "ServiceUnavailableError",
    "DuplicateTroubleshootingError",
    # 组件层异常
    "ParseFailedError",
    "ParseTimeoutError",
    "EmptyContentError",
    "SplitFailedError",
    "QueryEmptyError",
    "QueryEmbeddingFailedError",
    "DimensionMismatchError",
    "VectorDatabaseUnavailableError",
    "TemplateNotFoundError",
    "ToolValidationError",
    "ToolNotFoundError",
    "ToolNamingConflictError",
    "McpToolError",
    "McpToolTimeoutError",
    "McpConnectFailedError",
    "MemorySummarizeFailedError",
    "SourceFileNotFoundError",
    "SyncFailedError",
    "SendMsgFailedError",
    "TargetGroupUnavailableError",
    "ReplanLimitReachedError",
    "IterationLimitReachedError",
    "UnsupportedTechStackError",
    # ----- 核心数据模型 -----
    # Chunk
    "Chunk",
    # VectorRecord
    "VectorRecord",
    "VectorType",
    # Memory
    "Role",
    "Session",
    "Message",
    "ShortTermMemory",
    "LongTermSummary",
    # IngestTask
    "IngestTask",
    "IngestTaskStatus",
    # TroubleshootingTask
    "NO_CONTENT",
    "AlarmInfo",
    "AnalysisSummary",
    "ReportStatus",
    "TriggerType",
    "TroubleshootingTask",
    "TroubleshootingTaskStatus",
    # Plan / Step
    "Plan",
    "Step",
    "StepFailure",
    "StepResult",
    "StepStatus",
    "ReplanVerdict",
    # Tool
    "ParamDef",
    "ParamType",
    "ToolDefinition",
    "ToolSource",
]
